### ISSUE TITLE
error on macos 13.3

### ISSUE THREAD

**Issue by cburst** [kharvd/gpt-cli#10]
hi there-

i tried to run gpt-cli, but I got this error:

ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/Users/rescreen/gpt-cli/./gpt.py", line 191, in <module>
    main()
  File "/Users/rescreen/gpt-cli/./gpt.py", line 121, in main
    read_yaml_config(config_path) if os.path.isfile(config_path) else GptCliConfig()
  File "/Users/rescreen/gpt-cli/gptcli/config.py", line 23, in read_yaml_config
    return GptCliConfig(
TypeError: gptcli.config.GptCliConfig() argument after ** must be a mapping, not str
An uncaught exception occurred. Please report this issue on GitHub.
Traceback (most recent call last):
  File "/Users/rescreen/gpt-cli/./gpt.py", line 191, in <module>
    main()
  File "/Users/rescreen/gpt-cli/./gpt.py", line 121, in main
    read_yaml_config(config_path) if os.path.isfile(config_path) else GptCliConfig()
  File "/Users/rescreen/gpt-cli/gptcli/config.py", line 23, in read_yaml_config
    return GptCliConfig(
TypeError: gptcli.config.GptCliConfig() argument after ** must be a mapping, not str

**Comment by cburst** [comment]
i'm using python 3.10.9

**Comment by kharvd** [comment]
Do you have a `~/.gptrc` file? Is it a valid `yaml` file?
