### ISSUE TITLE
Model GPT-4 not found

### ISSUE THREAD

**Issue by gogl92** [kharvd/gpt-cli#33]
When I do
`gpt.py --model=gpt-4`

I got

```
Hi! I'm here to help. Type q or Ctrl-D to exit, c or Ctrl-C to clear the
conversation, r or Ctrl-R to re-generate the last response. To enter multi-line
mode, enter a backslash \ followed by a new line. Exit the multi-line mode by
pressing ESC and then Enter (Meta+Enter).
> are you chatgpt 4?


Request Error. The last prompt was not saved: <class 'openai.error.InvalidRequestError'>: The model: `gpt-4` does not exist
The model: `gpt-4` does not exist
Traceback (most recent call last):
  File "/Users/gogl92/PhpstormProjects/gpt-cli/gptcli/session.py", line 101, in _respond
    for response in completion_iter:
  File "/Users/gogl92/PhpstormProjects/gpt-cli/gptcli/openai.py", line 20, in complete
    openai.ChatCompletion.create(
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
```

**Comment by kharvd** [comment]
Sounds like you don't have access to GPT-4 API. https://openai.com/waitlist/gpt-4-api

**Comment by gogl92** [comment]
I'll verify the API key, thanks

**Comment by wookayin** [comment]
Even if the API doesn't have a permission, shouldn't the program handle an error nicely? (e.g. `gpt --model gpt-4` should print something rather than a raw stacktrace) --- *before* a prompt starts.
