### ISSUE TITLE
FileNotFoundError: Shared library with base name 'llama' not found

### ISSUE THREAD

**Issue by bastienGranger** [kharvd/gpt-cli#50]
Just followed the install step from readme file and getting this error

```
Traceback (most recent call last):
  File "gpt.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "gptcli/assistant.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "gptcli/llama.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "llama_cpp/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "llama_cpp/llama_cpp.py", line 73, in <module>
  File "llama_cpp/llama_cpp.py", line 64, in _load_shared_library
FileNotFoundError: Shared library with base name 'llama' not found
[58098] Failed to execute script 'gpt' due to unhandled exception!
```

Environment Info:
Mac OS Venture (13.4)
Python Version 3.11.2
Pip Version 23.1.2

**Comment by kharvd** [comment]
Did you install it with `pip install gpt-command-line`?
