### ISSUE TITLE
Problem with using pipe and reading from stdin

### ISSUE THREAD

**Issue by jakubgros** [kharvd/gpt-cli#57]
Hello. I have encountered a problem with the tool when I try to pipe in some text to it:

```
$ echo "hi" | gpt general
Warning: Input is not a terminal (fd=0).
Hi! I'm here to help. Type :q or Ctrl-D to exit, :c or Ctrl-C and Enter to clear
the conversation, :r or Ctrl-R to re-generate the last response. To enter
multi-line mode, enter a backslash \ followed by a new line. Exit the multi-line
mode by pressing ESC and then Enter (Meta+Enter). Try :? for help.
^[[36;1R> hi
Hello! How can I assist you today?

                                                    Tokens: 22 | Price: $0.000 | Total: $0.000
^[[40;1R>
Uncaught exception
Traceback (most recent call last):
  File "/home/kuba/.local/bin/gpt", line 8, in <module>
    sys.exit(main())
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/gpt.py", line 189, in main
    run_interactive(args, assistant)
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/gpt.py", line 237, in run_interactive
    session.loop(input_provider)
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/session.py", line 183, in loop
    while self.process_input(*input_provider.get_user_input()):
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 148, in get_user_input
    while (next_user_input := self._request_input()) == "":
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 197, in _request_input
    line = self.prompt()
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 186, in prompt
    return self.prompt_session.prompt(
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1035, in prompt
    return self.app.run(
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 961, in run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 875, in run_async
    return await _run_async(f)
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 740, in _run_async
    result = await f
EOFError
An uncaught exception occurred. Please report this issue on GitHub.
Traceback (most recent call last):
  File "/home/kuba/.local/bin/gpt", line 8, in <module>
    sys.exit(main())
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/gpt.py", line 189, in main
    run_interactive(args, assistant)
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/gpt.py", line 237, in run_interactive
    session.loop(input_provider)
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/session.py", line 183, in loop
    while self.process_input(*input_provider.get_user_input()):
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 148, in get_user_input
    while (next_user_input := self._request_input()) == "":
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 197, in _request_input
    line = self.prompt()
  File "/home/kuba/.local/lib/python3.10/site-packages/gptcli/cli.py", line 186, in prompt
    return self.prompt_session.prompt(
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1035, in prompt
    return self.app.run(
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 961, in run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 875, in run_async
    return await _run_async(f)
  File "/home/kuba/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 740, in _run_async
    result = await f
EOFError
```

I would expect it to work the same way as with the following syntax:

```
$ gpt general --prompt "$(echo hi)"
Hello! How can I assist you today?%
```

Could you advise if there is something I'm doing incorrectly or there is a bug in the tool?

**Comment by kharvd** [comment]
Try `echo "hi" | gpt general --prompt -`:

```
--prompt PROMPT, -p PROMPT
                        If specified, will not start an interactive chat session and instead will print the response to standard output and exit. May be specified multiple times.
                        Use `-` to read the prompt from standard input. Implies --no_markdown.
```
