### ISSUE TITLE
seems to throw when using new gpt4-turbo model

### ISSUE THREAD

**Issue by TimDaub** [kharvd/gpt-cli#59]
Hey are you planning to continue to maintain this, because I'm an active user

for new model https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

gpt-4-1106-preview

> hey
Hello! How can I assist you today?

Uncaught exception
Traceback (most recent call last):
  File "/Users/timdaub/Projects/gpt-cli/gpt.py", line 239, in <module>
    main()
  File "/Users/timdaub/Projects/gpt-cli/gpt.py", line 187, in main
    run_interactive(args, assistant)
  File "/Users/timdaub/Projects/gpt-cli/gpt.py", line 235, in run_interactive
    session.loop(input_provider)
  File "/Users/timdaub/Projects/gpt-cli/gptcli/session.py", line 168, in loop
    while self.process_input(*input_provider.get_user_input()):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timdaub/Projects/gpt-cli/gptcli/session.py", line 160, in process_input
    response_saved = self._respond(args)
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/timdaub/Projects/gpt-cli/gptcli/session.py", line 116, in _respond
    self.listener.on_chat_response(self.messages, next_message, args)
  File "/Users/timdaub/Projects/gpt-cli/gptcli/composite.py", line 59, in on_chat_response
    listener.on_chat_response(messages, response, overrides)
  File "/Users/timdaub/Projects/gpt-cli/gptcli/cost.py", line 142, in on_chat_response
    price = price_for_completion(messages, response, model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by TimDaub** [comment]
I added pricing to my fork. I'm sadly on an old version and I don't have the time to figure out how to setup the new thing, maybe another time! https://github.com/TimDaub/gpt-cli/commit/109880a1738f6a66051d497859840b229fe626d2
