### ISSUE TITLE
macos 12.6 hurdles

### ISSUE THREAD

**Issue by alandthompsongithub** [kharvd/gpt-cli#9]
Cleared a fair few hurdles to get this going using zsh.

Can't seem to get past this error:

`gpt-cli % python3 gpt.py
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/Users/adtm1x/gpt-cli/gpt.py", line 191, in <module>
    main()
  File "/Users/adtm1x/gpt-cli/gpt.py", line 132, in main
    read_yaml_config(config_path) if os.path.isfile(config_path) else GptCliConfig()
  File "/Users/adtm1x/gpt-cli/gptcli/config.py", line 23, in read_yaml_config
    return GptCliConfig(
TypeError: gptcli.config.GptCliConfig() argument after ** must be a mapping, not str
An uncaught exception occurred. Please report this issue on GitHub.
Traceback (most recent call last):
  File "/Users/adtm1x/gpt-cli/gpt.py", line 191, in <module>
    main()
  File "/Users/adtm1x/gpt-cli/gpt.py", line 132, in main
    read_yaml_config(config_path) if os.path.isfile(config_path) else GptCliConfig()
  File "/Users/adtm1x/gpt-cli/gptcli/config.py", line 23, in read_yaml_config
    return GptCliConfig(
TypeError: gptcli.config.GptCliConfig() argument after ** must be a mapping, not str`

**Comment by kharvd** [comment]
What is your Python version? I've been testing it with Python 3.9
```python3 --version```

**Comment by kharvd** [comment]
Do you have a `~/.gptrc` file? Is it a valid YAML file?
